-- Colors
CLR_BLACK = 0
CLR_DARK_BLUE = 1
CLR_DARK_PURPLE = 2
CLR_DARK_GREEN = 3
CLR_BROWN = 4
CLR_DARK_GREY = 5
CLR_LIGHT_GREY = 6
CLR_WHITE = 7
CLR_RED = 8
CLR_ORANGE = 9
CLR_YELLOW = 10
CLR_GREEN = 11
CLR_BLUE = 12
CLR_LAVENDER = 13
CLR_PINK = 14
CLR_LIGHT_PEACH = 15

-- Buttons
BUTTON_LEFT = 0
BUTTON_RIGHT = 1
BUTTON_UP = 2
BUTTON_DOWN = 3
BUTTON_O = 4
BUTTON_X = 5

-- General
DIRECTION_LEFT = -1
DIRECTION_NONE = 0
DIRECTION_RIGHT = 1

-- Sprites
SPR_PLAYER_START_LEFT = 62
SPR_PLAYER_START_RIGHT = 46
SPR_BG_1 = 16
SPR_BG_2 = 32
SPR_BG_3 = 52

-- Data Storage
DATA_DEATHS_IDX = 32
DATA_HISCORE_IDX = 33
DATA_HAS_DASH = 33

-- General
DASH_AQUIRED_LEVEL_NUMBER = 16
