-- Colors
CLR_BLACK = 0
CLR_DARK_BLUE = 1
CLR_DARK_PURPLE = 2
CLR_DARK_GREEN = 3
CLR_BROWN = 4
CLR_DARK_GREY = 5
CLR_LIGHT_GREY = 6
CLR_WHITE = 7
CLR_RED = 8
CLR_ORANGE = 9
CLR_YELLOW = 10
CLR_GREEN = 11
CLR_BLUE = 12
CLR_LAVENDER = 13
CLR_PINK = 14
CLR_LIGHT_PEACH = 15

-- Buttons
BUTTON_LEFT = 0
BUTTON_RIGHT = 1
BUTTON_UP = 2
BUTTON_DOWN = 3
BUTTON_O = 4
BUTTON_X = 5

-- General
DIRECTION_LEFT = -1
DIRECTION_NONE = 0
DIRECTION_RIGHT = 1

-- Sprites
SPR_PLAYER_START_LEFT = 62
SPR_PLAYER_START_RIGHT = 46
SPR_BG_1 = 16
SPR_BG_2 = 32
SPR_BG_3 = 52

-- Data Storage
DATA_DEATHS_IDX = 32
DATA_HISCORE_IDX = 33
DATA_HAS_DASH_IDX = 33
DATA_LEVEL_REACHED_IDX = 34

-- General
DASH_AQUIRED_LEVEL_NUMBER = 16
RESET_WAIT_TIME = 35
STARTING_LEVEL_NUM = 1
MENU_ITEM_RESTART_IDX = 1
MENU_ITEM_MAINMENU_IDX = 2

-- Special Characters
CHAR_BUTTON_O = "🅾️"
CHAR_BUTTON_X = "❎"
CHAR_BUTTON_LEFT = "⬅️"
CHAR_BUTTON_RIGHT = "➡️"
CHAR_TIME = "⧗"

-- SFX
SFX_JUMP = 0
SFX_COLLECT_POOP = 1
SFX_COLLECT_KEY = 2
SFX_TAKE_DAMAGE = 3
SFX_BUBBLE_POP = 4
SFX_LEVEL_CLEAR = 5
SFX_DASH = 6
SFX_MOVE_PROMPT = 7
SFX_MENU_OPT_SELECT = 8
SFX_MENU_ERROR = 9
SFX_MENU_ACCEPT = 10

-- Music
MUSIC_NONE = -1
MUSIC_WIN = 1
MUSIC_MENU = 2
MUSIC_OVER = 3
